In [26]:
a=[1,2,3]#List
print(a)
for i in range(len(a)):
    a[i]+=1
print(a)

[1, 2, 3]
[2, 3, 4]


In [7]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [5]:
import numpy as np

A=np.zeros((2,4),int)
print(A)

[[0 0 0 0]
 [0 0 0 0]]


In [8]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [14]:
e = np.empty([2, 3], dtype = int)
print(e)

[[1451565072        429          0]
 [         0          1          0]]


In [25]:
#การสร้าง Array
#a หมายถึงตัวแปรลำดับ หรือ array 
#ndmin คือ มิติ ของ array ที่ต้องการกำหนด
# dtype หมายถึงชนิดข้อมูล
#asarray แปลงขอมูลที่รับเข้ามาให ้ เป็น array 
#coppy coppy array ที่มีอยู่แล้ว
import numpy as np
a = np.array([[1, 2],[3,4]], dtype=int, ndmin=2)
np.asarray(a, dtype=int)
np.copy(a)

array([[1, 2],
       [3, 4]])

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [27]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [19]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [20]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [21]:
a = [1,2]
np.asarray(a)

array([1, 2])

In [38]:
a = np.array([[1, 2],[3,4]], dtype=np.float32)
np.asarray(a, dtype=np.float32)

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [39]:
import numpy as np
A=[[1,2,3,4,5,],[1,2,3,4,5,]]
print(A)
print(len(A[0]))
A=np.array(A,ndmin=2)
print(A)
print(A.shape)
print(A.size)
print(A.ndim)
print(A.dtype)
print(A.itemsize)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
5
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
10
2
int32
4


In [44]:
#numpy.arange เป็นการสรางค่าตัววเลขที่อยู่ภายในช่วงข้อมูลที่กำหนด
np.arange(3)

array([0, 1, 2])

In [45]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [46]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [27]:
np.arange(-50,-1,2)

array([-50, -48, -46, -44, -42, -40, -38, -36, -34, -32, -30, -28, -26,
       -24, -22, -20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2])

In [48]:
np.linspace(3.0,4.0,num = 5)

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [49]:
#endpoint ถ้าไม่กำหนดคือ default=True นั้นคือนับรวมจดสิ้นสุดด้วย
np.linspace(3.0,4.0,num = 5,endpoint = False)

array([3. , 3.2, 3.4, 3.6, 3.8])

In [29]:
#retstep  ถ้าไม่กำหนดคือ default= false
np.linspace(3.0,4.0,num = 5,retstep = True)

(array([3.  , 3.25, 3.5 , 3.75, 4.  ]), 0.25)

In [54]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3)) 

array([[0, 1, 2],
       [3, 0, 1]])

In [55]:
np.resize(a,(1,4)) 

array([[0, 1, 2, 3]])

In [97]:
np.resize(a,(1,6))

array([[10.5, 10.5, 10.5, 10.5, 10.5, 10.5]])

In [68]:
a = np.array([[0, 1],[ 2, 3]])
a.resize((2,1))
a

array([[0],
       [1]])

In [69]:
b = np.array([[0, 1],[ 2, 3]])
b.resize((2,3))
b

array([[0, 1, 2],
       [3, 0, 0]])

In [17]:
x = np.arange(1,21)
print(x)
x.resize(4,5)
x

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
a = np.arange(6)
print(a.reshape((3,2)))

[[0 1]
 [2 3]
 [4 5]]


In [24]:
y = np.sum(x,axis = 0)
z = np.sum(x,axis = 1)
print(y)
print(z)
a = np.sum(x)
a

[34 38 42 46 50]
[15 40 65 90]


210

In [19]:
y = np.mean(x,axis=0)
z = np.mean(x,axis=1)
print(y)
print(z)
a = np.mean(x)
a

[ 8.5  9.5 10.5 11.5 12.5]
[ 3.  8. 13. 18.]


10.5