In [30]:
import numpy as np 

# 7.1 ค่าเฉลี่ย (Mean) 
#ตัวแปร = numpy.mean(array, axis=None, dtype=None)
#array = ข้อมลู array 
#axis = dim หรือมติของ array ที่ต้องการให้คำนวณหาผลลัพธ์ถ้า axis = 0 หมายถึง
#หาผลลัพธ์ในแต่ละ column ถ้า axis = 1 หมายถึงให้หาผลลัพธ์ในแต่ ละ  row 
#dtype = ชนิดของข้อมูล

a = np.array([[1, 2], [3, 4]]) 
np.mean(a)

2.5

In [10]:
np.mean(a, axis=0) #column

array([2., 3.])

In [11]:
np.mean(a, axis=1) #column

array([1.5, 3.5])

In [23]:
b = np.array([1, 2, 3]) 
np.mean(b)

2.0

In [13]:
a = np.zeros((2, 512*512), dtype=np.float32) 
a[0, :] = 1.0 
a[1, :] = 0.1 
np.mean(a)

0.54999924

In [14]:
np.mean(a, dtype=np.float64)

0.5500000007450581

In [31]:
a = np.zeros((2,10))
print(a)
print(a.shape)
a[0,:]=1.0
print(a)
a[1, :]=0.2
print(a)
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
a[1,:]=0.1
print(np.mean(a,axis=1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(2, 10)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1.  1.  1.  1.  1.  1.  1.  1.  1.  1. ]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]
0.5999999999999999
[0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
[1.  0.2]
[1.  0.1]


In [19]:
# ค่าส่วนเบี่ยงเบนมาตรฐาน (Standard deviation)
a = np.array([[1,2,3],[4,5,6],[2,4,8]])
print(a)
print('mean =',np.mean(a))
print('variance(population) =',np.var(a))
print('variance(example) =',np.var(a,ddof=1))
print('std(pop) =',np.std(a))
print('std(ex) =' ,np.std(a,ddof=1))

[[1 2 3]
 [4 5 6]
 [2 4 8]]
mean = 3.888888888888889
variance(population) = 4.320987654320987
variance(example) = 4.861111111111111
std(pop) = 2.078698548207745
std(ex) = 2.204792759220492


In [42]:
import numpy as np
a=[[1,2,3],[4,5,6], [2,4, 8] ]
a=np.array(a)
print(np.median(a))
print(np.median(a,axis=1))
b=a.T
print(b)
print(np.median(b,axis=1))
a.resize(9)
print(a.shape)
print(np.sort(a))

4.0
[2. 5. 4.]
[[1 4 2]
 [2 5 4]
 [3 6 8]]
[2. 4. 6.]
(9,)
[1 2 2 3 4 4 5 6 8]


In [34]:
#ค่าฐานนิยม (Mode) 
import scipy.stats as st
a = [[1,2,3,4],[2,3,5,3],[4,3,1,0]]
a = np.array(a)
print(st.mode(a))
print(st.mode(a,axis = 1))
from scipy import stats
C = a.reshape(12)
print(C)
md, cnt = stats.mode(C)
print(md,cnt)
md, = stats.mode(C)
print(md)

ModeResult(mode=array([[1, 3, 1, 0]]), count=array([[1, 2, 1, 1]]))
ModeResult(mode=array([[1],
       [3],
       [0]]), count=array([[1],
       [2],
       [1]]))
[1 2 3 4 2 3 5 3 4 3 1 0]
[3] [4]


ValueError: too many values to unpack (expected 1)

In [39]:
a = [[1,2,3,4],[2,3,5,3], [4,3,1,0] ]
a = np.array(a)
print(st.mode(a))
print(st.mode(a,axis=1))
print(st.mode(a,axis=None))
from scipy import stats
C=a.reshape(12)
print(C)
md=stats.mode(C)
print(md[0])
md, cnt =stats.mode(C)
print(md,cnt)
md, =stats.mode(C)
print(md)

ModeResult(mode=array([[1, 3, 1, 0]]), count=array([[1, 2, 1, 1]]))
ModeResult(mode=array([[1],
       [3],
       [0]]), count=array([[1],
       [2],
       [1]]))
ModeResult(mode=array([3]), count=array([4]))
[1 2 3 4 2 3 5 3 4 3 1 0]
[3]
[3] [4]


ValueError: too many values to unpack (expected 1)